### ISSUE TITLE
Difference Midtrans & Veritrans

### ISSUE THREAD

**Issue by andriaripratama** [harrypujianto/Veritrans-Laravel5#18]
Hi!

I see from your libs, you have 2 class. Midtrans and Veritrans. What's the different between both of them? Can I use only one of them? Or should both?

Also, from original documentation, there's isSanitized and is3ds options. But, I see form your libs there's nothing I can find this. Is that not important here or there's another way to perform that kinda option.

Thank you!

**Comment by robertnicjoo** [comment]
@andriaripratama let me save your time, getting answer here could be pain in the ass :)


1-
`Midtrans` is uses for POP-UP transaction form (SNAP)
`Veritrans` is uses in order to redirect user to third-party website for transaction and redirect them back after it's done (regardless transaction was successful or not).

2-
It's optional which one to use (your choice)

3-
`isSanitized `,  `is3ds ` I have no idea, maybe official supporters can help you, but if i'm not mistake `is3ds ` is for credit card process (it will ask for card password before start transaction process) `yet, is just an opinion they should answer you about this`


Hope it helps.

**Comment by andriaripratama** [comment]
Hi @robertnicjoo Thanks for ASAP.

1- & 2- Noted.
3. Yap, I will ask to official supporters.

Thank you for your help.
